/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "bar_ewmhtags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "cfacts.c"
#include "cool_autostart.c"
#include "dragcfact.c"
#include "fullscreen.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "rotatestack.c"
#include "scratchpad.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_monocle.c"
#include "layout_tile.c"
